version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # HTTP → redirection vers HTTPS
      - "3443:3443"  # HTTPS réel
    volumes:
      - ./src/ssl:/app/src/ssl:ro  # monte les certificats dans le conteneur
    environment:
      - NODE_ENV=development
    command: ["node", "src/server.js"]

