name: CI/CD Vagrant + Ansible

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint-code:
    name: Lint Vagrant + Ansible
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Vérifier et installer Vagrant si nécessaire
        run: |
          echo " Vérification de Vagrant..."
          if ! command -v vagrant &> /dev/null; then
            echo " Vagrant non trouvé, installation..."
            sudo apt-get update
            sudo apt-get install -y wget gnupg software-properties-common
            wget -q https://apt.releases.hashicorp.com/gpg -O- | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
              sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update
            sudo apt-get install -y vagrant
          else
            echo " Vagrant déjà installé."
          fi

      - name: Validation du Vagrantfile
        working-directory: ./vagrant
        run: |
          echo " Validation du Vagrantfile..."
          vagrant validate

      - name: Installer ansible-lint
        run: |
          echo " Installation d'ansible-lint..."
          sudo apt update
          sudo apt install -y ansible-lint

      - name: Lint des playbooks Ansible
        working-directory: ./ansible
        run: |
          echo " Lint des playbooks Ansible..."
          ansible-lint playbooks/site.yml

  deploy-infra:
    name: Déploiement VMs + Ansible
    runs-on: self-hosted
    needs: lint-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Ansible et dépendances
        run: |
          echo " Installation d'Ansible et dépendances..."
          sudo apt update
          sudo apt install -y ansible sshpass python3-pymysql

      - name: Démarrer les VMs avec Vagrant
        working-directory: ./vagrant
        run: |
          echo " Lancement des machines virtuelles..."
          vagrant up --provider=virtualbox
          vagrant status

      - name: Exécuter le playbook Ansible
        working-directory: ./ansible
        run: |
          echo " Déploiement avec Ansible..."
          ansible-playbook -i inventories/dev/hosts.yml playbooks/site.yml

  test-infra:
    name: Test Infrastructure (Testinfra)
    runs-on: self-hosted
    needs: deploy-infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Testinfra & Pytest
        run: |
          echo " Installation de Testinfra et Pytest..."
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install testinfra pytest

      - name: Lancer les tests d'infrastructure
        working-directory: ./tests
        run: |
          echo " Exécution des tests d'infra avec pytest..."
          pytest -v
