name: Analyse Qualité & Sécurité

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Installer les dépendances
      run: npm ci

    - name: Lint + Fix du code
      run: npx eslint . --fix

    - name: Analyse de vulnérabilités
      run: npm audit --audit-level=high
